<h2>Login using this form</h2>

<?php echo $this->tag->form("login/login"); ?>
    <p>Latest SignUp Email: <?php echo $this->session->get('data')['email'] ?> </p>
    <p>Latest SignUp Password: <?php echo $this->session->get('data')['password'] ?> </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton(["Login","class"=>"btn btn-primary"]); ?>
    </p>

</form>